### PR TITLE
Removing both Amarok and Inxi from lists.

### PR DESCRIPTION
**Pull request by FredBezies**
Both are now on AUR. See: https://aur.archlinux.org/packages/amarok/ and https://aur.archlinux.org/packages/inxi/

### CODE REVIEW

**Comment by condor2** [comment]
inxi is already in anarchy repo

**Comment by FredBezies** [comment]
OK. And Amarok? For inxi, moving it in Anarchy repo list could be the best to do... I think.

**Comment by condor2** [comment]
amarok was added one hour ago... :)

**Comment by FredBezies** [comment]
So there is a little change which can be made in lib/configure_base.sh Not everyone will activate anarchy repository.

It is your choice now :)

**Comment by FredBezies** [comment]
Removing patch as it is no longer necessary.

**Comment by condor2** [comment]
I moved now that 3 packages: inxi, scite, amarok to $aar

**Pull request closed without merging**
