### PR TITLE
Add TIMEOUT to boot menu

### PR DESCRIPTION
**Pull request by PandaFoss**
Add TIMEOUT to solve #791

### CODE REVIEW

**Comment by JustMeErazem** [comment]
Hi, I just stumbled upon your pull request. I see you set the timeout to 50 seconds, isn't that a bit too much. Any user with a normal keyboard (meaning he can choose what to boot) will have chosen his settings long before the 50 seconds would be up and the countdown stops when selecting anyway, so (and this is just my opinion), wouldn't it make sense to set it to something like 10 seconds, so users like sudoquai (submitter of #791) don't have that long to boot.

**Comment by PandaFoss** [comment]
> Hi, I just stumbled upon your pull request. I see you set the timeout to 50 seconds, isn't that a bit too much? Any user with a normal keyboard (meaning he can choose what to boot) will have chosen his settings long before the 50 seconds would be up and the countdown stops when selecting anyway, so (and this is just my opinion), wouldn't it make sense to set it to something like 10 seconds, so users like sudoquai (submitter of #791) don't have to wait that long to boot?

It's not 50 seconds, it's 5 seconds...

**Comment by sudoquai** [comment]
5 seconds is perfect - thx a lot @PandaFoss

**Comment by JustMeErazem** [comment]
@PandaFoss line 5 of [archiso_head.cfg](https://github.com/PandaFoss/panda-linux/blob/5e6f344906b3db20e3fe12251a3649608f846f62/boot/iso/archiso_head.cfg) says "TIMEOUT 50".

**Comment by PandaFoss** [comment]
> @PandaFoss line 5 of [archiso_head.cfg](https://github.com/PandaFoss/panda-linux/blob/5e6f344906b3db20e3fe12251a3649608f846f62/boot/iso/archiso_head.cfg) says "TIMEOUT 50".

That´s because `TIMEOUT` value is in units of 0.1 seconds.

**Comment by JustMeErazem** [comment]
I don't know this by heart or have the computer with me atm, but I believe it is in seconds. Here's an extract from [Ostechnix](https://www.ostechnix.com/configure-grub-2-boot-loader-settings-ubuntu-16-04/): "If the value is “5” , the boot menu will appear for 5 seconds..."

**Comment by PandaFoss** [comment]
In any case, I always build the ISO image and test it in a virtual machine before proposing the changes here...

**Pull request merged**
