### PR TITLE
fix for sed regex

### PR DESCRIPTION
**Pull request by dszryan**
sed regex was too greedy and was causing issues

### CODE REVIEW

**Comment by dszryan** [comment]
pfa hotfix for the install_base.sh script

**Comment by cabaalexander** [comment]
Out of curiosity, what kinds of issues ? 🤔

**Comment by dszryan** [comment]
it was replacing "linux-firmware" as well leaving "-firmware"
and thus giving an error unknown command -f

**Comment by dszryan** [comment]
> Out of curiosity, what kinds of issues ? 🤔

it was replacing "linux-firmware" as well, leaving "-firmware"
and thus giving an error unknown command -f

**Pull request merged**
